### ISSUE TITLE
Tensorflow on Pepper

### ISSUE THREAD

**Issue by SilviaSantano** [arotyramel/NaoQiObjectReco#1]
Hi, I have one question, which method did you use to install tensorflow on Nao robot?
I'm trying to install it on Pepper robot but it is resulting really hard since we do not have root permissions on Pepper robot... so it is very hard to install something. I compiled bazel and tensorflow for 32 bits on a different machine and copied it but I'm still having trouble with other dependencies (libc)...

**Comment by de-code** [comment]
Hi Silvia,

Thank you for reaching out.

As this was for a hackathon, we actually were running it on a laptop and communicated with the NAO via WiFi.

Hope you are getting it to work.

Daniel

**Comment by SilviaSantano** [comment]
Hi Daniel,

thanks a lot for you quick reply! OK I see, this is also my plan B if I don’t get it to work on the robot itself :)
Thanks again for the info.

Silvia
